# Generated by Django 5.1.2 on 2024-12-24 13:08

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="facilities",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("central_ac", "Central A/C"),
                    ("maids_room", "Maids Room"),
                    ("balcony", "Balcony"),
                    ("shared_pool", "Shared Pool"),
                    ("shared_spa", "Shared Spa"),
                    ("shared_gym", "Shared Gym"),
                    ("concierge_service", "Concierge Service"),
                    ("covered_parking", "Covered Parking"),
                    ("view_of_water", "View of Water"),
                    ("view_of_landmark", "View of Landmark"),
                    ("pets_allowed", "Pets Allowed"),
                    ("study", "Study"),
                    ("private_garden", "Private Garden"),
                    ("private_pool", "Private Pool"),
                    ("private_gym", "Private Gym"),
                    ("private_jacuzzi", "Private Jacuzzi"),
                    ("built_in_wardrobes", "Built in Wardrobes"),
                    ("walk_in_closet", "Walk-in Closet"),
                    ("built_in_kitchen_appliances", "Built in Kitchen Appliances"),
                    ("maid_service", "Maid Service"),
                    ("childrens_play_area", "Children's Play Area"),
                    ("childrens_pool", "Children's Pool"),
                    ("barbecue_area", "Barbecue Area"),
                ],
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("agent", "Agent")],
                default="buyer",
                max_length=10,
            ),
        ),
    ]
