# Generated by Django 5.1.2 on 2025-01-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_alter_property_facilities_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communities",
                to="property.agent",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.FileField(upload_to="properties/images"),
        ),
    ]
