# Generated by Django 5.1.2 on 2025-01-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_property_slug_alter_community_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
