# Generated by Django 5.1.2 on 2025-01-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_community_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
