# Generated by Django 5.1.2 on 2025-01-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_alter_community_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="slug",
            field=models.SlugField(default="No slug", max_length=100),
        ),
    ]
